add main service
OrlovDeniss/java-explore-with-me pull request #4
Opened 2023-07-24 12:04 UTC by OrlovDeniss

2023-07-24 16:27 UTC, OrlovDeniss commented
Добрый день!

2023-07-24 19:38 UTC, andrew-larkin requested changes
Привет! Отличная реализация нового функционала! Остается немного скорректировать модели и будем готовы приступать к последнему этапу.

2023-07-24 19:38 UTC, andrew-larkin commented on ewm-service/src/main/java/ru/practicum/category/controller/admin/CategoryAdminControllerImpl.java
> +    public ResponseEntity<Object> deleteCategoryByAdmin(Integer catId) {
если метод void, можно использовать не Object, а специальный класс Void

2023-07-24 19:38 UTC, andrew-larkin commented on ewm-service/src/main/java/ru/practicum/category/model/Category.java
> +@Data
@Data для моделей лучше не использовать - она может некорректно рассчитывать хэш. Лучше заменить ее на аннотации @Getter, @Setter и т.п.

2023-07-24 19:38 UTC, andrew-larkin commented on ewm-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    @ManyToMany
мне кажется, тут стоит прописать связь более явным образом - указать id из двух таблиц, которые мы пытаемся связать и прописать их название в соединительной таблице

2023-07-25 04:19 UTC, OrlovDeniss commented
Благодарю за ревью! проект доработан)

2023-07-26 02:01 UTC, merged